name: Publish

on:
  push:
    tags: 
      - release-*
        
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Publish
        run: dotnet publish -c Release -r linux-x64 --self-contained=false -o deploy
        
      - name: Deploy
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ GITHUB_WORKSPACE }}/deploy 
          remote: ~/image-service
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSK_KEY }}