name: Publish

on:
  push:
    branches: [ master ]
#    tags: 
#      - release-*
        
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Publish
        run: dotnet publish -c Release -r linux-x64 --self-contained=false -o deploy
        
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          source: ${{ github.workspace }}/deploy 
          target: ~/image-service
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSK_KEY }}
          rm: true